package com.google.android.youtube.player;

public enum C6825f {
    EMBEDDING_DISABLED,
    BLOCKED_FOR_APP,
    NOT_PLAYABLE,
    NETWORK_ERROR,
    UNAUTHORIZED_OVERLAY,
    PLAYER_VIEW_TOO_SMALL,
    PLAYER_VIEW_NOT_VISIBLE,
    EMPTY_PLAYLIST,
    AUTOPLAY_DISABLED,
    USER_DECLINED_RESTRICTED_CONTENT,
    USER_DECLINED_HIGH_BANDWIDTH,
    UNEXPECTED_SERVICE_DISCONNECTION,
    INTERNAL_ERROR,
    UNKNOWN
}
