package com.google.android.finsky.api;

import android.net.Uri;

public final class C1286g {
    public static final Uri f7630A = Uri.parse("checkPromoOffer");
    public static final Uri f7631B = Uri.parse("billingProfile");
    public static final Uri f7632C = Uri.parse("log");
    public static final Uri f7633D = Uri.parse("flagContent");
    public static final Uri f7634E = Uri.parse("ack");
    public static final Uri f7635F = Uri.parse("acceptTos");
    public static final Uri f7636G = Uri.parse("library");
    public static final Uri f7637H = Uri.parse("ees/bulkAcquire");
    public static final Uri f7638I = Uri.parse("bulkDetails");
    public static final Uri f7639J = Uri.parse("skuDetails");
    public static final Uri f7640K = Uri.parse("resolveLink");
    public static final Uri f7641L = Uri.parse("replicateLibrary");
    public static final Uri f7642M = Uri.parse("delivery");
    public static final Uri f7643N = Uri.parse("moduleDelivery");
    public static final Uri f7644O = Uri.parse("modifyLibrary");
    public static final Uri f7645P = Uri.parse("consumePurchase");
    public static final Uri f7646Q = Uri.parse("inAppPurchaseHistory");
    public static final Uri f7647R = Uri.parse("uploadDeviceConfig");
    public static final Uri f7648S = Uri.parse("accountSync");
    public static final Uri f7649T = Uri.parse("earlyUpdate");
    public static final Uri f7650U = Uri.parse("earlyDelivery");
    public static final Uri f7651V = Uri.parse("preloads");
    public static final Uri f7652W = Uri.parse("redeemCode");
    public static final Uri f7653X = Uri.parse("contentFilterSettings");
    public static final Uri f7654Y = Uri.parse("verifyAge");
    public static final Uri f7655Z = Uri.parse("ping");
    public static final Uri f7656a = Uri.parse("https://android.clients.google.com/fdfe/");
    public static final Uri aA = Uri.parse("apps/preregistration");
    public static final Uri aB = Uri.parse("dismissAssistCards");
    public static final Uri aC = Uri.parse("updateNotificationCenterState");
    public static final Uri aa = Uri.parse("userSetting");
    public static final Uri ab = Uri.parse("userSettings");
    public static final Uri ac = Uri.parse("documentSharingState");
    public static final Uri ad = Uri.parse("updateFamilySharingSettings");
    public static final Uri ae = Uri.parse("getFamilySharingSettings");
    public static final Uri af = Uri.parse("setFamilyPurchaseSetting");
    public static final Uri ag = Uri.parse("getFamilyMemberSetting");
    public static final Uri ah = Uri.parse("bulkSharing");
    public static final Uri ai = Uri.parse("getFamilySetupOptions");
    public static final Uri aj = Uri.parse("createRemoteEscalation");
    public static final Uri ak = Uri.parse("listRemoteEscalation");
    public static final Uri al = Uri.parse("updateRemoteEscalation");
    public static final Uri am = Uri.parse("getRemoteEscalationNotification");
    public static final Uri an = Uri.parse("monetaryGiftDetails");
    public static final Uri ao = Uri.parse("getGiftShareText");
    public static final Uri ap = Uri.parse("managedConfigurations");
    public static final Uri aq = Uri.parse("apps/checkLicense");
    public static final Uri ar = Uri.parse("apps/contentSync");
    public static final Uri as = Uri.parse("apps/testingProgram");
    public static final Uri at = Uri.parse("story");
    public static final Uri au = Uri.parse("bulkDataFetch");
    public static final Uri av = Uri.parse("resolveWebApk");
    public static final Uri aw = Uri.parse("richUserNotification");
    public static final Uri ax = Uri.parse("contactEmail");
    public static final Uri ay = Uri.parse("updateContactEmail");
    public static final Uri az = Uri.parse("customerProfile");
    public static final Uri f7657b = Uri.parse("toc");
    public static final Uri f7658c = Uri.parse("selfUpdate");
    public static final Uri f7659d = Uri.parse("search");
    public static final Uri f7660e = Uri.parse("searchSuggest");
    public static final Uri f7661f = Uri.parse("apps/launcherSearchSuggest");
    public static final Uri f7662g = Uri.parse("debugSettings");
    public static final Uri f7663h = Uri.parse("mySubscriptions");
    public static final Uri f7664i = Uri.parse("myRewards");
    public static final Uri f7665j = Uri.parse("purchaseHistory");
    public static final Uri f7666k = Uri.parse("confirmSubscriptionPriceChange");
    public static final Uri f7667l = Uri.parse("updateSubscriptionInstrument");
    public static final Uri f7668m = Uri.parse("reactivateSubscription");
    public static final Uri f7669n = Uri.parse("addReview");
    public static final Uri f7670o = Uri.parse("deleteReview");
    public static final Uri f7671p = Uri.parse("rateReview");
    public static final Uri f7672q = Uri.parse("purchase");
    public static final Uri f7673r = Uri.parse("ees/preparePurchase");
    public static final Uri f7674s = Uri.parse("ees/commitPurchase");
    public static final Uri f7675t = Uri.parse("acquire");
    public static final Uri f7676u = Uri.parse("ees/acquire");
    public static final Uri f7677v = Uri.parse("revoke");
    public static final Uri f7678w = Uri.parse("familyFop");
    public static final Uri f7679x = Uri.parse("checkInstrument");
    public static final Uri f7680y = Uri.parse("getBackupDeviceChoices");
    public static final Uri f7681z = Uri.parse("getBackupDocumentChoices");

    static {
        Uri.parse("subscriptionsCenter");
        Uri.parse("getFamilyPurchaseSetting");
        Uri.parse("dataPlan");
    }
}
