package com.google.android.finsky.bd;

import com.squareup.leakcanary.C7582R;

public final class C1592a {
    public static final Integer f8426A = Integer.valueOf(C7582R.id.subscribe_button);
    public static final Integer f8427B = Integer.valueOf(C7582R.id.upsell_button);
    public static final Integer f8428C = Integer.valueOf(C7582R.layout.artist_subscription_upsell_module);
    public static final Integer f8429D = Integer.valueOf(C7582R.id.warm_welcome_v2_close_btn);
    public static final Integer f8430E = Integer.valueOf(C7582R.id.warm_welcome_v2_brand_logo);
    public static final Integer f8431F = Integer.valueOf(C7582R.layout.music_merch_banner);
    public static final Integer f8432G = Integer.valueOf(C7582R.id.music_merch_banner_title_group);
    public static final Integer f8433H = Integer.valueOf(C7582R.id.music_merch_title_subtitle_spacer);
    public static final Integer f8434I = Integer.valueOf(C7582R.id.music_merch_subtitle_button_spacer);
    public static final Integer f8435J = Integer.valueOf(C7582R.id.music_merch_close_btn);
    public static final Integer f8436K = Integer.valueOf(C7582R.id.music_merch_banner_title);
    public static final Integer f8437L = Integer.valueOf(C7582R.id.music_merch_banner_subtitle);
    public static final Integer f8438M = Integer.valueOf(C7582R.id.music_merch_banner_button);
    public static final Integer f8439N = Integer.valueOf(C7582R.id.music_merch_logo);
    public static final Integer f8440O = Integer.valueOf(C7582R.id.music_merch_image);
    public static final Integer f8441P = Integer.valueOf(C7582R.dimen.music_merch_banner_button_stroke_width);
    public static final Integer f8442Q = Integer.valueOf(C7582R.layout.music_home_upsell_bottom_sheet);
    public static final Integer f8443R = Integer.valueOf(C7582R.drawable.ic_play_music_logo);
    public static final Integer f8444S = Integer.valueOf(C7582R.drawable.ic_play_music_logo_white);
    public static final Integer f8445T = Integer.valueOf(C7582R.id.play_music_logo);
    public static final Integer f8446U = Integer.valueOf(C7582R.id.play_music_logo_white);
    public static final Integer f8447V = Integer.valueOf(C7582R.id.header_no_image);
    public static final Integer f8448W = Integer.valueOf(C7582R.id.header_with_image);
    public static final Integer f8449X = Integer.valueOf(C7582R.id.play_music_header_image_view);
    public static final Integer f8450Y = Integer.valueOf(C7582R.string.music_home_microsite_subscribe);
    public static final Integer f8451Z = Integer.valueOf(C7582R.string.content_description_audiobook_title);
    public static final Integer f8452a = Integer.valueOf(C7582R.string.remote_escalation_title_parent);
    public static final Integer aA = Integer.valueOf(C7582R.id.notification_center_card_icon);
    public static final Integer aB = Integer.valueOf(C7582R.id.notification_center_card_bottom_spacer);
    public static final Integer aC = Integer.valueOf(C7582R.raw.logo_play_prism_192px_clr);
    public static final Integer aD = Integer.valueOf(C7582R.drawable.notification_center_card_red_dot);
    public static final Integer aE = Integer.valueOf(C7582R.dimen.notification_center_header_bottom_margin_offset);
    public static final Integer aa = Integer.valueOf(C7582R.string.content_description_thumbnail_audiobook);
    public static final Integer ab = Integer.valueOf(C7582R.string.rate_this_audiobook);
    public static final Integer ac = Integer.valueOf(C7582R.string.ebook_buy);
    public static final Integer ad = Integer.valueOf(C7582R.string.audiobook_buy);
    public static final Integer ae = Integer.valueOf(C7582R.string.ebook_free_buy);
    public static final Integer af = Integer.valueOf(C7582R.string.audiobook_free_buy);
    public static final Integer ag = Integer.valueOf(C7582R.string.play_sample);
    public static final Integer ah = Integer.valueOf(C7582R.string.pause_sample);
    public static final Integer ai = Integer.valueOf(C7582R.string.resume_sample);
    public static final Integer aj = Integer.valueOf(C7582R.string.prepare_sample);
    public static final Integer ak = Integer.valueOf(C7582R.string.play_audiobook);
    public static final Integer al = Integer.valueOf(C7582R.string.sample_play_error);
    public static final Integer am = Integer.valueOf(C7582R.id.orson_title_creator_block);
    public static final Integer an = Integer.valueOf(C7582R.id.orson_creator_title);
    public static final Integer ao = Integer.valueOf(C7582R.id.orson_title_line);
    public static final Integer ap = Integer.valueOf(C7582R.id.orson_creator_date);
    public static final Integer aq = Integer.valueOf(C7582R.layout.orson_extra_bottom_labels);
    public static final Integer ar = Integer.valueOf(C7582R.string.notification_center);
    public static final Integer as = Integer.valueOf(C7582R.layout.notification_results);
    public static final Integer at = Integer.valueOf(C7582R.layout.play_card_notification);
    public static final Integer au = Integer.valueOf(C7582R.layout.play_card_notification_terms);
    public static final Integer av = Integer.valueOf(C7582R.id.notification_center_card_title);
    public static final Integer aw = Integer.valueOf(C7582R.id.notification_center_card_message);
    public static final Integer ax = Integer.valueOf(C7582R.id.notification_center_card_timestamp);
    public static final Integer ay = Integer.valueOf(C7582R.id.notification_primary_cta);
    public static final Integer az = Integer.valueOf(C7582R.id.notification_secondary_cta);
    public static final Integer f8453b = Integer.valueOf(C7582R.string.remote_escalation_title_kid);
    public static final Integer f8454c = Integer.valueOf(C7582R.string.remote_escalation_pending_tab);
    public static final Integer f8455d = Integer.valueOf(C7582R.string.remote_escalation_history_tab);
    public static final Integer f8456e = Integer.valueOf(C7582R.string.remote_escalation_parent_page_title);
    public static final Integer f8457f = Integer.valueOf(C7582R.string.remote_escalation_approve);
    public static final Integer f8458g = Integer.valueOf(C7582R.string.remote_escalation_deny);
    public static final Integer f8459h = Integer.valueOf(C7582R.menu.family_remote_escalation);
    public static final Integer f8460i = Integer.valueOf(C7582R.id.approve_all);
    public static final Integer f8461j = Integer.valueOf(C7582R.string.remote_escalation_approve_all_dialog_title);
    public static final Integer f8462k = Integer.valueOf(C7582R.layout.family_remote_escalation_bulk_approve_dialog);
    public static final Integer f8463l = Integer.valueOf(C7582R.layout.family_remote_escalation_approval_dialog);
    public static final Integer f8464m = Integer.valueOf(C7582R.id.approval_loading_indicator);
    public static final Integer f8465n = Integer.valueOf(C7582R.id.auth_challenge);
    public static final Integer f8466o = Integer.valueOf(C7582R.id.formatted_price);
    public static final Integer f8467p = Integer.valueOf(C7582R.id.approve_button);
    public static final Integer f8468q = Integer.valueOf(C7582R.id.deny_button);
    public static final Integer f8469r = Integer.valueOf(C7582R.layout.deeplink_disconnection_notification_requested);
    public static final Integer f8470s = Integer.valueOf(C7582R.layout.disconnection_page);
    public static final Integer f8471t = Integer.valueOf(C7582R.id.notify_button);
    public static final Integer f8472u = Integer.valueOf(C7582R.string.deeplink_loading_network_error_body);
    public static final Integer f8473v = Integer.valueOf(C7582R.string.reconnection_notification_title);
    public static final Integer f8474w = Integer.valueOf(C7582R.string.reconnection_notification_title_details);
    public static final Integer f8475x = Integer.valueOf(C7582R.string.reconnection_notification_message);
    public static final Integer f8476y = Integer.valueOf(C7582R.string.all_access_button_listen_free);
    public static final Integer f8477z = Integer.valueOf(C7582R.string.all_access_button_listen_free_alt);

    static {
        Integer.valueOf(C7582R.string.setup_wizard_play_add_fop_title);
        Integer.valueOf(C7582R.layout.family_remote_escalation_card_view);
        Integer.valueOf(C7582R.string.notification_center_caught_up);
        Integer.valueOf(C7582R.string.notification_center_empty_explanation);
    }
}
