package com.google.protobuf;

public enum ay {
    IS_INITIALIZED,
    GET_MEMOIZED_IS_INITIALIZED,
    SET_MEMOIZED_IS_INITIALIZED,
    MERGE_FROM_STREAM,
    MAKE_IMMUTABLE,
    NEW_MUTABLE_INSTANCE,
    NEW_BUILDER,
    GET_DEFAULT_INSTANCE,
    GET_PARSER
}
