package com.google.android.gms.internal;

import android.content.Context;
import com.google.android.gms.ads.p270c.C4909c;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.TimeUnit;

@C5302b
public final class yu {
    public static final yk f27745a = yk.m26004a("gads:sdk_crash_report_enabled", Boolean.valueOf(false));
    public static final yk f27746b = yk.m26004a("gads:sdk_crash_report_full_stacktrace", Boolean.valueOf(false));
    public static final yk f27747c = yk.m26005a("gads:sdk_crash_report_class_prefix", "com.google.");
    public static yk f27748d = yk.m26002a("gads:heap_wastage:bytes", 0);
    public static final yk f27749e = yk.m26004a("gads:log:verbose_enabled", Boolean.valueOf(false));
    public static final yk f27750f = yk.m26004a("gads:adshield:enable_adshield_instrumentation", Boolean.valueOf(false));
    public static final yk f27751g = yk.m26003a("gads:gestures:task_timeout", 2000);
    public static final yk f27752h = yk.m26004a("gads:gestures:encrypt_size_limit:enabled", Boolean.valueOf(false));
    public static final yk f27753i = yk.m26004a("gads:gestures:orn_caching:enabled", Boolean.valueOf(true));
    public static final yk f27754j = yk.m26004a("gads:gestures:oc:enabled", Boolean.valueOf(false));
    public static final yk f27755k = yk.m26002a("gads:gestures:ts", 1);
    public static final yk f27756l = yk.m26004a("gads:gestures:td:enabled", Boolean.valueOf(false));
    public static final yk f27757m = yk.m26004a("gads:gestures:tdvs:enabled", Boolean.valueOf(false));
    public static final yk f27758n = yk.m26004a("gads:gestures:tuvs:enabled", Boolean.valueOf(false));
    public static final yk f27759o = yk.m26004a("gads:gestures:tvvs:enabled", Boolean.valueOf(false));
    public static final yk f27760p = yk.m26004a("gads:gestures:vd:enabled", Boolean.valueOf(false));
    public static final yk f27761q = yk.m26005a("gads:gestures:pk", "");
    public static final yk f27762r = yk.m26004a("gads:gestures:bs:enabled", Boolean.valueOf(true));
    public static final yk f27763s = yk.m26004a("gads:gestures:check_initialization_thread:enabled", Boolean.valueOf(false));
    public static final yk f27764t = yk.m26004a("gads:gestures:get_query_in_non_ui_thread:enabled", Boolean.valueOf(true));
    public static final yk f27765u = yk.m26004a("gass:enabled", Boolean.valueOf(true));
    public static final yk f27766v = yk.m26004a("gass:enable_int_signal", Boolean.valueOf(true));
    public static final yk f27767w = yk.m26004a("gass:enable_ad_attestation_signal", Boolean.valueOf(true));
    public static byte[] f27768x;

    static {
        yk.m26006b("gads:sdk_core_experiment_id");
        yk.m26005a("gads:sdk_core_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.html");
        yk.m26004a("gads:request_builder:singleton_webview", Boolean.valueOf(false));
        yk.m26006b("gads:request_builder:singleton_webview_experiment_id");
        yk.m26004a("gads:sdk_use_dynamic_module", Boolean.valueOf(true));
        yk.m26006b("gads:sdk_use_dynamic_module_experiment_id");
        yk.m26004a("gads:block_autoclicks", Boolean.valueOf(false));
        yk.m26006b("gads:block_autoclicks_experiment_id");
        yk.m26006b("gads:spam_app_context:experiment_id");
        yk.m26004a("gads:spam_app_context:enabled", Boolean.valueOf(false));
        yk.m26002a("gads:http_url_connection_factory:timeout_millis", 10000);
        yk.m26005a("gads:video_exo_player:version", "1");
        yk.m26006b("gads:video_stream_cache:experiment_id");
        yk.m26002a("gads:video_stream_cache:limit_count", 5);
        yk.m26002a("gads:video_stream_cache:limit_space", 8388608);
        yk.m26002a("gads:video_stream_exo_allocator:segment_size", 65536);
        yk.m26002a("gads:video_stream_exo_cache:buffer_size", 8388608);
        yk.m26003a("gads:video_stream_cache:limit_time_sec", 300);
        yk.m26003a("gads:video_stream_cache:notify_interval_millis", 125);
        yk.m26002a("gads:video_stream_cache:connect_timeout_millis", 10000);
        yk.m26004a("gads:video:metric_reporting_enabled", Boolean.valueOf(false));
        yk.m26005a("gads:video:metric_frame_hash_times", "");
        yk.m26003a("gads:video:metric_frame_hash_time_leniency", 500);
        yk.m26004a("gads:video:force_watermark", Boolean.valueOf(false));
        yk.m26003a("gads:video:surface_update_min_spacing_ms", 1000);
        yk.m26004a("gads:video:spinner:enabled", Boolean.valueOf(false));
        yk.m26002a("gads:video:spinner:scale", 4);
        yk.m26003a("gads:video:spinner:jank_threshold_ms", 50);
        yk.m26004a("gads:video:aggressive_media_codec_release", Boolean.valueOf(false));
        yk.m26004a("gads:memory_bundle:debug_info", Boolean.valueOf(false));
        yk.m26004a("gads:memory_bundle:runtime_info", Boolean.valueOf(true));
        yk.m26005a("gads:video:codec_query_mime_types", "");
        yk.m26002a("gads:video:codec_query_minimum_version", 16);
        yk.m26004a("gads:ad_id_app_context:enabled", Boolean.valueOf(false));
        yk.m26001a("gads:ad_id_app_context:ping_ratio");
        yk.m26006b("gads:ad_id_app_context:experiment_id");
        yk.m26006b("gads:ad_id_use_shared_preference:experiment_id");
        yk.m26004a("gads:ad_id_use_shared_preference:enabled", Boolean.valueOf(false));
        yk.m26001a("gads:ad_id_use_shared_preference:ping_ratio");
        yk.m26007c("gads:looper_for_gms_client:experiment_id");
        yk.m26004a("gads:looper_for_gms_client:enabled", Boolean.valueOf(true));
        yk.m26004a("gads:sw_ad_request_service:enabled", Boolean.valueOf(true));
        yk.m26004a("gads:sw_dynamite:enabled", Boolean.valueOf(true));
        yk.m26005a("gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_banner.js");
        yk.m26005a("gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_expanded_banner.js");
        yk.m26005a("gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_interstitial.js");
        yk.m26004a("gads:enabled_sdk_csi", Boolean.valueOf(false));
        yk.m26005a("gads:sdk_csi_server", "https://csi.gstatic.com/csi");
        yk.m26004a("gads:sdk_csi_write_to_file", Boolean.valueOf(false));
        yk.m26004a("gads:enable_content_fetching", Boolean.valueOf(true));
        yk.m26002a("gads:content_length_weight", 1);
        yk.m26002a("gads:content_age_weight", 1);
        yk.m26002a("gads:min_content_len", 11);
        yk.m26002a("gads:fingerprint_number", 10);
        yk.m26002a("gads:sleep_sec", 10);
        yk.m26004a("gads:enable_content_url_hash", Boolean.valueOf(true));
        yk.m26002a("gads:content_vertical_fingerprint_number", 100);
        yk.m26004a("gads:enable_content_vertical_hash", Boolean.valueOf(true));
        yk.m26002a("gads:content_vertical_fingerprint_bits", 23);
        yk.m26002a("gads:content_vertical_fingerprint_ngram", 3);
        yk.m26005a("gads:content_fetch_view_tag_id", "googlebot");
        yk.m26005a("gads:content_fetch_exclude_view_tag", "none");
        yk.m26004a("gad:app_index_enabled", Boolean.valueOf(true));
        yk.m26004a("gads:content_fetch_disable_get_title_from_webview", Boolean.valueOf(false));
        yk.m26004a("gads:app_index:without_content_info_present:enabled", Boolean.valueOf(true));
        yk.m26003a("gads:app_index:timeout_ms", 1000);
        yk.m26006b("gads:app_index:experiment_id");
        yk.m26006b("gads:kitkat_interstitial_workaround:experiment_id");
        yk.m26004a("gads:kitkat_interstitial_workaround:enabled", Boolean.valueOf(true));
        yk.m26004a("gads:interstitial_follow_url", Boolean.valueOf(true));
        yk.m26004a("gads:interstitial_follow_url:register_click", Boolean.valueOf(true));
        yk.m26006b("gads:interstitial_follow_url:experiment_id");
        yk.m26004a("gads:analytics_enabled", Boolean.valueOf(true));
        yk.m26004a("gads:ad_key_enabled", Boolean.valueOf(false));
        yk.m26004a("gads:sai:enabled", Boolean.valueOf(false));
        yk.m26004a("gads:sai:banner_ad_enabled", Boolean.valueOf(true));
        yk.m26004a("gads:sai:native_ad_enabled", Boolean.valueOf(true));
        yk.m26004a("gads:sai:interstitial_ad_enabled", Boolean.valueOf(true));
        yk.m26004a("gads:sai:rewardedvideo_ad_enabled", Boolean.valueOf(true));
        yk.m26005a("gads:sai:click_ping_schema", "[\"/aclk\",\"/pcs/click\"]");
        yk.m26005a("gads:sai:impression_ping_schema", "[\"/adview\"]");
        yk.m26004a("gads:sai:click_gmsg_enabled", Boolean.valueOf(true));
        yk.m26004a("gads:sai:using_macro:enabled", Boolean.valueOf(false));
        yk.m26005a("gads:sai:ad_event_id_macro_name", "[gw_fbsaeid]");
        yk.m26003a("gads:sai:timeout_ms", 100);
        yk.m26002a("gads:sai:scion_thread_pool_size", 5);
        yk.m26002a("gads:webview_cache_version", 0);
        yk.m26004a("gads:webview_recycle:enabled", Boolean.valueOf(false));
        yk.m26004a("gads:webview:ignore_over_scroll", Boolean.valueOf(true));
        yk.m26007c("gads:pan:experiment_id");
        yk.m26004a("gads:rewarded:adapter_initialization_enabled", Boolean.valueOf(false));
        yk.m26003a("gads:rewarded:adapter_timeout_ms", 20000);
        yk.m26004a("gads:app_activity_tracker:enabled", Boolean.valueOf(true));
        yk.m26003a("gads:app_activity_tracker:notify_background_listeners_delay_ms", 500);
        yk.m26003a("gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5));
        yk.m26004a("gads:adid_values_in_adrequest:enabled", Boolean.valueOf(false));
        yk.m26003a("gads:adid_values_in_adrequest:timeout", 2000);
        yk.m26004a("gads:disable_adid_values_in_ms", Boolean.valueOf(false));
        yk.m26004a("gads:enable_ad_loader_manager", Boolean.valueOf(true));
        yk.m26004a("gads:ad_serving:enabled", Boolean.valueOf(true));
        yk.m26004a("gads:ad_manager_enforce_arp_invariant:enabled", Boolean.valueOf(false));
        yk.m26003a("gads:ad_overlay:delay_page_close_timeout_ms", 5000);
        yk.m26004a("gads:interstitial_ad_immersive_mode", Boolean.valueOf(true));
        yk.m26004a("gads:impression_optimization_enabled", Boolean.valueOf(false));
        yk.m26005a("gads:banner_ad_pool:schema", "customTargeting");
        yk.m26002a("gads:banner_ad_pool:max_queues", 3);
        yk.m26002a("gads:banner_ad_pool:max_pools", 3);
        yk.m26004a("gads:interstitial_ad_pool:enabled", Boolean.valueOf(false));
        yk.m26004a("gads:interstitial_ad_pool:enabled_for_rewarded", Boolean.valueOf(false));
        yk.m26005a("gads:interstitial_ad_pool:schema", "customTargeting");
        yk.m26005a("gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
        yk.m26002a("gads:interstitial_ad_pool:max_pools", 3);
        yk.m26002a("gads:interstitial_ad_pool:max_pool_depth", 2);
        yk.m26002a("gads:interstitial_ad_pool:time_limit_sec", 1200);
        yk.m26005a("gads:interstitial_ad_pool:ad_unit_exclusions", "(?!)");
        yk.m26002a("gads:interstitial_ad_pool:top_off_latency_min_millis", 0);
        yk.m26002a("gads:interstitial_ad_pool:top_off_latency_range_millis", 0);
        yk.m26003a("gads:interstitial_ad_pool:discard_thresholds", 0);
        yk.m26003a("gads:interstitial_ad_pool:miss_thresholds", 0);
        yk.m26001a("gads:interstitial_ad_pool:discard_asymptote");
        yk.m26001a("gads:interstitial_ad_pool:miss_asymptote");
        yk.m26005a("gads:spherical_video:vertex_shader", "");
        yk.m26005a("gads:spherical_video:fragment_shader", "");
        yk.m26004a("gads:include_local_global_rectangles", Boolean.valueOf(false));
        yk.m26003a("gads:position_watcher:throttle_ms", 200);
        yk.m26004a("gads:include_lock_screen_apps_for_visibility", Boolean.valueOf(true));
        yk.m26004a("gads:device_info_caching:enabled", Boolean.valueOf(true));
        yk.m26003a("gads:device_info_caching_expiry_ms:expiry", 300000);
        yk.m26004a("gads:gen204_signals:enabled", Boolean.valueOf(false));
        yk.m26004a("gads:webview:error_reporting_enabled", Boolean.valueOf(false));
        yk.m26004a("gads:adid_reporting:enabled", Boolean.valueOf(false));
        yk.m26004a("gads:ad_settings_page_reporting:enabled", Boolean.valueOf(false));
        yk.m26004a("gads:adid_info_gmscore_upgrade_reporting:enabled", Boolean.valueOf(false));
        yk.m26004a("gads:request_pkg:enabled", Boolean.valueOf(true));
        yk.m26004a("gads:gmsg:disable_back_button:enabled", Boolean.valueOf(true));
        yk.m26004a("gads:gmsg:video_meta:enabled", Boolean.valueOf(true));
        yk.m26006b("gads:gmsg:video_meta:experiment_id");
        yk.m26003a("gads:network:cache_prediction_duration_s", 300);
        yk.m26003a("gads:network:network_prediction_timeout_ms", 2000);
        yk.m26004a("gads:mediation:dynamite_first:admobadapter", Boolean.valueOf(true));
        yk.m26004a("gads:mediation:dynamite_first:adurladapter", Boolean.valueOf(true));
        yk.m26004a("gads:bypass_adrequest_service_for_inlined_mediation", Boolean.valueOf(true));
        yk.m26003a("gads:resolve_future:default_timeout_ms", 30000);
        yk.m26003a("gads:ad_loader:timeout_ms", 60000);
        yk.m26003a("gads:rendering:timeout_ms", 60000);
        yk.m26004a("gads:adid_notification:first_party_check:enabled", Boolean.valueOf(true));
        yk.m26004a("gads:edu_device_helper:enabled", Boolean.valueOf(true));
        yk.m26004a("gads:support_screen_shot", Boolean.valueOf(true));
        yk.m26004a("gads:use_get_drawing_cache_for_screenshot:enabled", Boolean.valueOf(true));
        yk.m26006b("gads:use_get_drawing_cache_for_screenshot:experiment_id");
        yk.m26006b("gads:sdk_core_constants:experiment_id");
        yk.m26005a("gads:sdk_core_constants:caps", "");
        yk.m26003a("gads:js_flags:update_interval", TimeUnit.HOURS.toMillis(12));
        yk.m26004a("gads:js_flags:mf", Boolean.valueOf(false));
        yk.m26004a("gads:custom_render:ping_on_ad_rendered", Boolean.valueOf(false));
        yk.m26005a("gads:native:engine_url", "//googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
        yk.m26005a("gads:native:engine_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
        yk.m26005a("gads:native:video_url", "//googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_video_ads.html");
        yk.m26005a("gads:native:video_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_video_ads.html");
        yk.m26004a("gads:singleton_webview_native", Boolean.valueOf(false));
        yk.m26004a("gads:native_initialize_webview_request_time", Boolean.valueOf(false));
        yk.m26006b("gads:singleton_webview_native:experiment_id");
        yk.m26004a("gads:enable_untrack_view_native", Boolean.valueOf(true));
        yk.m26004a("gads:ignore_untrack_view_google_native", Boolean.valueOf(true));
        yk.m26004a("gads:reset_listeners_preparead_native", Boolean.valueOf(true));
        yk.m26002a("gads:native_video_load_timeout", 10);
        yk.m26005a("gads:ad_choices_content_description", "Ad Choices Icon");
        yk.m26004a("gads:clamp_native_video_player_dimensions", Boolean.valueOf(true));
        yk.m26004a("gads:enable_store_active_view_state", Boolean.valueOf(false));
        yk.m26002a("gads:max_number_of_native_ads_allowed", 5);
        yk.m26004a("gads:fluid_ad:use_wrap_content_height", Boolean.valueOf(false));
        yk.m26004a("gads:method_tracing:enabled", Boolean.valueOf(false));
        yk.m26003a("gads:method_tracing:duration_ms", 30000);
        yk.m26002a("gads:method_tracing:count", 5);
        yk.m26002a("gads:method_tracing:filesize", 134217728);
        yk.m26004a("gads:auto_location_for_coarse_permission", Boolean.valueOf(false));
        yk.m26007c("gads:auto_location_for_coarse_permission:experiment_id");
        yk.m26003a("gads:auto_location_timeout", 2000);
        yk.m26007c("gads:auto_location_timeout:experiment_id");
        yk.m26003a("gads:auto_location_interval", -1);
        yk.m26007c("gads:auto_location_interval:experiment_id");
        yk.m26004a("gads:fetch_app_settings_using_cld:enabled", Boolean.valueOf(false));
        yk.m26006b("gads:fetch_app_settings_using_cld:enabled:experiment_id");
        yk.m26003a("gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000);
        yk.m26006b("gads:afs:csa:experiment_id");
        yk.m26005a("gads:afs:csa_webview_gmsg_ad_failed", "gmsg://noAdLoaded");
        yk.m26005a("gads:afs:csa_webview_gmsg_script_load_failed", "gmsg://scriptLoadFailed");
        yk.m26005a("gads:afs:csa_webview_gmsg_ad_loaded", "gmsg://adResized");
        yk.m26005a("gads:afs:csa_webview_static_file_path", "/afs/ads/i/webview.html");
        yk.m26005a("gads:afs:csa_webview_custom_domain_param_key", "csa_customDomain");
        yk.m26003a("gads:afs:csa_webview_adshield_timeout_ms", 1000);
        yk.m26004a("gads:afs:csa_ad_manager_enabled", Boolean.valueOf(true));
        yk.m26004a("gads:parental_controls:send_from_client", Boolean.valueOf(true));
        yk.m26004a("gads:parental_controls:cache_results", Boolean.valueOf(true));
        yk.m26003a("gads:parental_controls:timeout", 2000);
        yk.m26005a("gads:safe_browsing:api_key", "AIzaSyDRKQ9d6kfsoZT2lUnZcZnBYvH69HExNPE");
        yk.m26003a("gads:safe_browsing:safety_net:delay_ms", 2000);
        yk.m26004a("gads:safe_browsing:debug", Boolean.valueOf(false));
        yk.m26004a("gads:webview_cookie:enabled", Boolean.valueOf(true));
        yk.m26002a("gads:cache:ad_request_timeout_millis", 250);
        yk.m26002a("gads:cache:max_concurrent_downloads", 10);
        yk.m26003a("gads:cache:javascript_timeout_millis", 5000);
        yk.m26004a("gads:cache:bind_on_foreground", Boolean.valueOf(false));
        yk.m26004a("gads:cache:bind_on_init", Boolean.valueOf(false));
        yk.m26004a("gads:cache:bind_on_request", Boolean.valueOf(false));
        yk.m26003a("gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30));
        yk.m26004a("gads:cache:use_cache_data_source", Boolean.valueOf(false));
        yk.m26004a("gads:cache:connection_per_read", Boolean.valueOf(false));
        yk.m26003a("gads:cache:connection_timeout", 5000);
        yk.m26003a("gads:cache:read_only_connection_timeout", 5000);
        yk.m26004a("gads:chrome_custom_tabs:enabled", Boolean.valueOf(true));
        yk.m26004a("gads:chrome_custom_tabs_browser:enabled", Boolean.valueOf(false));
        yk.m26004a("gads:chrome_custom_tabs:disabled", Boolean.valueOf(false));
        yk.m26004a("gads:drx_in_app_preview:enabled", Boolean.valueOf(true));
        yk.m26004a("gads:drx_debug_signals:enabled", Boolean.valueOf(true));
        yk.m26005a("gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
        yk.m26005a("gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
        yk.m26005a("gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
        yk.m26005a("gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
        yk.m26002a("gads:drx_debug:timeout_ms", 5000);
        yk.m26002a("gad:pixel_dp_comparision_multiplier", 1);
        yk.m26004a("gad:interstitial_for_multi_window", Boolean.valueOf(false));
        yk.m26004a("gad:interstitial_ad_stay_active_in_multi_window", Boolean.valueOf(false));
        yk.m26002a("gad:interstitial:close_button_padding_dip", 0);
        yk.m26004a("gads:clearcut_logging:enabled", Boolean.valueOf(false));
        yk.m26004a("gads:clearcut_abtest:enabled", Boolean.valueOf(false));
        yk.m26002a("gads:clearcut_messageTime:ms", 60000);
        yk.m26004a("gad:force_local_ad_request_service:enabled", Boolean.valueOf(false));
        yk.m26002a("gad:http_redirect_max_count:times", 8);
        yk.m26004a("gads:nonagon:red_button", Boolean.valueOf(false));
        yk.m26004a("gads:nonagon:banner:enabled", Boolean.valueOf(false));
        yk.m26005a("gads:nonagon:banner:ad_unit_exclusions", "(?!)");
        yk.m26004a("gads:nonagon:interstitial:enabled", Boolean.valueOf(false));
        yk.m26005a("gads:nonagon:interstitial:ad_unit_exclusions", "(?!)");
        yk.m26004a("gads:nonagon:rewardedvideo:enabled", Boolean.valueOf(false));
        yk.m26005a("gads:nonagon:rewardedvideo:ad_unit_exclusions", "(?!)");
        yk.m26004a("gads:nonagon:service:enabled", Boolean.valueOf(false));
        yk.m26003a("gads:mobius_linking:sdk_side_cooldown_time_threshold:ms", 3600000);
    }

    public static void m26016a(Context context) {
        ak.m24180a(new yv(context));
        int intValue = ((Integer) C4909c.m22927a().f25267g.m26014a(f27748d)).intValue();
        if (intValue > 0 && f27768x == null) {
            f27768x = new byte[intValue];
        }
    }

    public static List m26015a() {
        yq yqVar = C4909c.m22927a().f25265e;
        List arrayList = new ArrayList();
        for (yk a : yqVar.f27737b) {
            String str = (String) C4909c.m22927a().f25267g.m26014a(a);
            if (str != null) {
                arrayList.add(str);
            }
        }
        return arrayList;
    }
}
